name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "27 4 * * 1"
  push:
    branches: ["master", "main"]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6 # v4.2.2
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@dc50aa9510b46c811795eb24b2f1ba02a914e534 # v2.3.3
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: false
      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v4  # v4
        with:
          sarif_file: scorecard.sarif
      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@v6 # v4.4.3
        with:
          name: scorecard-sarif
          path: scorecard.sarif
